import React from 'react';
import { AlertCircle, Clock, Database, Layers } from 'lucide-react';

const ProblemStats = () => {
  const stats = [
    {
      icon: <Layers className="text-teal-500" size={32} />,
      title: "10+ Disconnected Sources",
      description: "Drone imagery, cadastral maps, and municipal records sit in silos with no unified pipeline."
    },
    {
      icon: <Clock className="text-teal-500" size={32} />,
      title: "Slow Manual Workflows",
      description: "Labor-intensive GIS integration causes immense delays in urban land administration."
    },
    {
      icon: <AlertCircle className="text-teal-500" size={32} />,
      title: "Error-Prone Integration",
      description: "Manual alignment leads to boundary overlaps, gaps, and inconsistent property records."
    },
    {
      icon: <Database className="text-teal-500" size={32} />,
      title: "Delayed Finalization",
      description: "Weeks of manual verification required before a cadastral record can be officially finalized."
    }
  ];

  return (
    <section id="problem" className="py-20 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 transition-colors duration-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl font-bold text-navy-900 dark:text-white mb-4">The Challenge in Urban Land Records</h2>
          <p className="text-lg text-slate-600 dark:text-slate-300">
            Current systems struggle to efficiently process the massive volume of geospatial data generated by modern survey programs, leading to bottlenecks and inaccuracies.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {stats.map((stat, index) => (
            <div key={index} className="bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 p-6 rounded-lg shadow-sm hover:shadow-md transition-all duration-300 flex flex-col items-center text-center">
              <div className="bg-white dark:bg-slate-800 p-4 rounded-full shadow-sm mb-6 border border-slate-100 dark:border-slate-700">
                {stat.icon}
              </div>
              <h3 className="text-xl font-semibold text-navy-800 dark:text-slate-100 mb-3">{stat.title}</h3>
              <p className="text-slate-600 dark:text-slate-300 text-sm leading-relaxed">
                {stat.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default ProblemStats;
